language: c

install:
  - sudo apt-get update
  - sudo apt-get install g++ cmake make libqt4-dev

before_script:
  - git submodule update --init

script:
  - mkdir build-dir
  - cd build-dir
  - cmake ..
  - make
